services:
  db:
    image: mariadb:12.1
    restart: unless-stopped
    environment:
      TZ: Europe/Berlin
      MARIADB_ROOT_PASSWORD: $MARIADB_ROOT_PASSWORD
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: wordpress
      MARIADB_AUTO_UPGRADE: 1
    volumes:
      - ./db:/var/lib/mysql
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "5"

  redis:
    image: redis:latest
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./redis:/data
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  wordpress:
    depends_on:
      - db
      - redis
    build: .
    image: mmilesmm/wordpress-apache-php-fix:latest
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - ./wordpress_data:/var/www/html
      - ./wordpress.ini:/usr/local/etc/php/conf.d/wordpress.ini
    ports:
      - "127.0.0.1:${WEB_PORT:-3000}:80"
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "5"
